#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
从 NIST ACVP 的 ML-KEM KAT（internalProjection.json）生成 C++ 头文件
runtime/include/qchain/primitives/ml_kem_kat.hpp，用于逐字节比对验证 ML-KEM-768。

用法：
    py scripts/gen_mlkem_kat.py <keyGen.json> <encapDecap.json> [输出头文件]
"""
import json
import sys


def main():
    kg_path = sys.argv[1]
    enc_path = sys.argv[2]
    out_path = sys.argv[3] if len(sys.argv) > 3 else "runtime/include/qchain/primitives/ml_kem_kat.hpp"

    kg = json.load(open(kg_path, encoding="utf-8"))
    enc = json.load(open(enc_path, encoding="utf-8"))

    g768 = [g for g in kg["testGroups"] if g.get("parameterSet") == "ML-KEM-768"][0]
    t = g768["tests"][0]
    eg768 = [g for g in enc["testGroups"] if g.get("parameterSet") == "ML-KEM-768"][0]
    et = eg768["tests"][0]

    d, z = t["d"], t["z"]
    ek, dk = t["ek"], t["dk"]
    enc_ek, enc_dk = et["ek"], et["dk"]
    m, c, k = et["m"], et["c"], et["k"]

    def fn(name, s):
        # 折行 + 拼接，生成返回字符串字面量的函数
        parts = []
        for i in range(0, len(s), 64):
            parts.append('"%s"' % s[i:i + 64])
        body = "\n        ".join(parts)
        return 'inline const char* %s() { return\n        %s; }' % (name, body)

    src = """#pragma once
// ML-KEM-768 KAT vectors (NIST ACVP internalProjection, count 0).
// Auto-generated by scripts/gen_mlkem_kat.py - DO NOT EDIT.
// Source: github.com/usnistgov/ACVP-Server  gen-val/json-files/ML-KEM-*-FIPS203
// Purpose: byte-exact verification of MlKem768 against FIPS 203.
namespace qchain_kat {
%s
}
""" % "\n".join([fn("D", d), fn("Z", z), fn("EK", ek), fn("DK", dk),
                 fn("ENC_EK", enc_ek), fn("ENC_DK", enc_dk),
                 fn("M", m), fn("C", c), fn("K", k)])

    open(out_path, "w", encoding="utf-8", newline="\n").write(src)
    print("[gen_mlkem_kat] wrote %s" % out_path)


if __name__ == "__main__":
    main()
