#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""从 NIST ACVP 的 ML-DSA keyGen KAT（internalProjection.json）生成 C++ 头文件
runtime/include/qchain/primitives/ml_dsa_kat.hpp，用于逐字节比对验证 ML-DSA-65 密钥生成。

用法：
    py scripts/gen_mldsa_kat.py <keyGen.json> [输出头文件]
"""
import json
import sys


def main():
    kg_path = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "runtime/include/qchain/primitives/ml_dsa_kat.hpp"

    kg = json.load(open(kg_path, encoding="utf-8"))
    g = [g for g in kg["testGroups"] if g.get("parameterSet") == "ML-DSA-65"][0]
    t = g["tests"][0]

    seed, pk, sk = t["seed"], t["pk"], t["sk"]

    def fn(name, s):
        parts = []
        for i in range(0, len(s), 64):
            parts.append('"%s"' % s[i:i + 64])
        body = "\n        ".join(parts)
        return 'inline const char* %s() { return\n        %s; }' % (name, body)

    src = """#pragma once
// ML-DSA-65 KeyGen KAT vectors (NIST ACVP internalProjection, count 0).
// Auto-generated by scripts/gen_mldsa_kat.py - DO NOT EDIT.
// Source: github.com/usnistgov/ACVP-Server  gen-val/json-files/ML-DSA-keyGen-FIPS204
namespace qchain_kat {
%s
}
""" % "\n".join([fn("DSA_SEED", seed), fn("DSA_PK", pk), fn("DSA_SK", sk)])

    open(out, "w", encoding="utf-8", newline="\n").write(src)
    print("[gen_mldsa_kat] wrote %s (seed %d, pk %d, sk %d bytes)"
          % (out, len(seed) // 2, len(pk) // 2, len(sk) // 2))


if __name__ == "__main__":
    main()
